DROP TABLE IF EXISTS public.books CASCADE;

CREATE TABLE IF NOT EXISTS public.books
(
    id SERIAL,
    name varchar(100),
    author varchar(100),
	reader_id integer,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.readers CASCADE;

CREATE TABLE IF NOT EXISTS public.readers
(
    id SERIAL,
    email varchar(100),
    telegram varchar(100),
    book_id int,
    password varchar(100),
	role varchar(100),
	name varchar(100),
	CONSTRAINT readers_pk
		PRIMARY KEY (id),
	CONSTRAINT readers_books_id_fk
		FOREIGN KEY (book_id) REFERENCES books (id) 
);

DROP TABLE IF EXISTS public.message_table;

CREATE TABLE IF NOT EXISTS public.message_table
(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
	message varchar(255),
	PRIMARY KEY (id)
)

